export enum CardType {
  DUCHESS = 'DUCHESS',
  COUNTESS = 'COUNTESS',
  AMBASSADOR = 'AMBASSADOR',
  ASSASSIN = 'ASSASSIN',
  CAPTAIN = 'CAPTAIN',
}

export enum ActionType {
  PICK_COIN_1 = 'PICK_COIN_1',
  PICK_COIN_2 = 'PICK_COIN_2',
  PICK_COIN_3 = 'PICK_COIN_3',
  LIE = 'LIE',
  KILL_COIN_3 = 'KILL_COIN_3',
  KILL_COIN_7 = 'KILL_COIN_7',
  ROB_COIN = 'ROB_COIN',
  BLOCK_KILL = 'BLOCK_KILL',
  BLOCK_ROB = 'BLOCK_ROB',
  BLOCK_PICK = 'BLOCK_PICK',
  CHOOSE_CARD = 'CHOOSE_CARD',
  TRADE_CARDS = 'TRADE_CARDS',
}
